# Generated by Django 2.2.7 on 2020-01-11 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='ID чата пользователя в Telegram')),
                ('username', models.CharField(max_length=50, verbose_name='Логин пользователя')),
                ('name', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('program_type', models.CharField(max_length=50, verbose_name='Тип программы')),
                ('gender', models.CharField(max_length=30, verbose_name='Пол')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('weight', models.IntegerField(verbose_name='Вес (кг)')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Список профилей',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
                ('type', models.CharField(max_length=11, verbose_name='Тип программы')),
                ('gender', models.CharField(max_length=8, verbose_name='Пол')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.Profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Данные',
                'verbose_name_plural': 'Данные',
            },
        ),
    ]
