# Generated by Django 2.2.7 on 2020-01-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_auto_20200111_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес (кг)'),
        ),
    ]
