# Generated by Django 2.2.7 on 2020-01-13 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_auto_20200111_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Логин пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения заявки')),
                ('nutrition_goal', models.TextField(max_length=20, verbose_name='Цель')),
                ('how_much', models.IntegerField(verbose_name='Количество кг')),
                ('if_meat', models.CharField(max_length=15, verbose_name='Мясо')),
                ('if_milk', models.CharField(max_length=15, verbose_name='Молочка')),
                ('phys_loads', models.TextField(max_length=150, verbose_name='Нагрузка')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.Profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Данные по программам питания',
                'verbose_name_plural': 'Данные по программам питания',
            },
        ),
        migrations.CreateModel(
            name='Training_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Логин пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения заявки')),
                ('train_goal', models.TextField(max_length=20, verbose_name='Цель')),
                ('how_much', models.IntegerField(verbose_name='Количество кг')),
                ('sport_lvl', models.CharField(max_length=15, verbose_name='Уровень спортсмена')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.Profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Данные по программам тренировок',
                'verbose_name_plural': 'Данные по программам тренировок',
            },
        ),
        migrations.CreateModel(
            name='Vitamin_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Логин пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения заявки')),
                ('phys_loads', models.TextField(max_length=150, verbose_name='Нагрузка')),
                ('stress', models.CharField(max_length=15, verbose_name='Стресс')),
                ('weakness', models.CharField(max_length=15, verbose_name='Слабость')),
                ('sun_frequency', models.CharField(max_length=10, verbose_name='Солнце')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ugc.Profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Данные по программам витаминов',
                'verbose_name_plural': 'Данные по программам витаминов',
            },
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
