# Generated by Django 2.2.7 on 2020-01-13 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0004_auto_20200113_1434'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nutrition_Data',
            new_name='Nutrition',
        ),
        migrations.RenameModel(
            old_name='Training_Data',
            new_name='Training',
        ),
        migrations.RenameModel(
            old_name='Vitamin_Data',
            new_name='Vitamin',
        ),
    ]
