# Generated by Django 3.0.3 on 2020-02-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0008_payments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payments',
            options={'verbose_name': 'Данные по плате', 'verbose_name_plural': 'Данные по платежам'},
        ),
        migrations.AlterField(
            model_name='payments',
            name='key_succ',
            field=models.CharField(max_length=200, verbose_name='Ключ'),
        ),
    ]
